# Generated by Django 3.1.7 on 2021-06-29 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('building', '0003_auto_20210629_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_area', models.IntegerField(blank=True)),
                ('num_of_persons', models.PositiveIntegerField(default=0)),
                ('payment_status', models.BooleanField(choices=[(True, 'Paid'), (False, 'Unpaid')], default=True, null=True)),
                ('debt', models.FloatField(default=0)),
                ('number_id', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.building')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_counter', models.IntegerField(default=0, null=True)),
                ('status', models.BooleanField(blank=True, choices=[(True, 'Active'), (False, 'Disabled')], default=False, null=True)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.apartment')),
                ('utility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.utility')),
            ],
        ),
        migrations.CreateModel(
            name='MutualUtility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.apartment')),
                ('utility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.utility')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartment.tenant'),
        ),
    ]
