# Generated by Django 3.1.7 on 2021-06-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='surface_area',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
