# Generated by Django 3.1.7 on 2021-04-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_individualutil'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='num_identifier',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
