# Generated by Django 3.1.7 on 2021-04-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_apartment_num_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='num_identifier',
        ),
    ]
