# Generated by Django 3.1.7 on 2021-04-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0002_auto_20210408_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='tax_type',
            field=models.BooleanField(choices=[(True, 'Per Person'), (False, 'Per Apartment')], null=True),
        ),
    ]
