# Generated by Django 3.1.7 on 2021-04-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0004_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='cold_water_main_payment',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='gas_power_main_payment',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='heating_power_main_payment',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='hot_water_main_payment',
            field=models.FloatField(default=0, null=True),
        ),
    ]
