# Generated by Django 3.1.7 on 2021-04-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0007_mainutil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainutil',
            old_name='parent',
            new_name='util',
        ),
    ]
