# Generated by Django 3.1.7 on 2021-04-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0008_auto_20210420_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='_index_counter',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='MainUtil',
        ),
    ]
