# Generated by Django 3.1.7 on 2021-04-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0009_auto_20210420_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='cold_water_main_index',
        ),
        migrations.RemoveField(
            model_name='building',
            name='gas_power_main_index',
        ),
        migrations.RemoveField(
            model_name='building',
            name='heating_power_main_index',
        ),
        migrations.RemoveField(
            model_name='building',
            name='hot_water_main_index',
        ),
        migrations.RemoveField(
            model_name='utility',
            name='_index_counter',
        ),
    ]
