# Generated by Django 3.1.7 on 2021-04-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0011_auto_20210420_1807'),
        ('residential', '0011_mainutil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainUtil',
        ),
    ]
