# Generated by Django 3.1.7 on 2021-04-21 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0012_delete_mainutil'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUtil',
            fields=[
                ('utility_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='residential.utility')),
            ],
            bases=('residential.utility', models.Model),
        ),
    ]
