# Generated by Django 3.1.7 on 2021-04-21 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0014_delete_mainutil'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUtil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_counter', models.IntegerField(default=0, null=True)),
                ('util', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.utility')),
            ],
        ),
    ]
