# Generated by Django 3.1.7 on 2021-03-26 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_persons', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='cleaning_wages',
        ),
        migrations.RemoveField(
            model_name='building',
            name='cold_water_index_counter',
        ),
        migrations.RemoveField(
            model_name='building',
            name='cold_water_unit_tax',
        ),
        migrations.RemoveField(
            model_name='building',
            name='gas_power_index_counter',
        ),
        migrations.RemoveField(
            model_name='building',
            name='gas_power_unit_tax',
        ),
        migrations.RemoveField(
            model_name='building',
            name='heating_power_index_counter',
        ),
        migrations.RemoveField(
            model_name='building',
            name='heating_power_unit_tax',
        ),
        migrations.RemoveField(
            model_name='building',
            name='hot_water_index_counter',
        ),
        migrations.RemoveField(
            model_name='building',
            name='hot_water_unit_tax',
        ),
        migrations.RemoveField(
            model_name='building',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='building',
            name='sanitation_tax',
        ),
        migrations.CreateModel(
            name='CommonUtils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('util_status', models.BooleanField(choices=[(True, 'Active'), (False, 'Disabled')], default=True)),
                ('util_index', models.IntegerField(default=0)),
                ('util_tax', models.BooleanField(default=0)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.apartment')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.building')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.building'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
