# Generated by Django 3.1.7 on 2021-06-25 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=100, null=True)),
                ('street_number', models.PositiveIntegerField()),
                ('postal_code', models.CharField(max_length=10, null=True)),
                ('apartments_capacity', models.PositiveIntegerField()),
                ('admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('util_type', models.CharField(choices=[('Mutual', 'Mutual'), ('Individual', 'Individual')], max_length=20, null=True)),
                ('provider', models.CharField(choices=[('City', 'City'), ('Private', 'Private')], max_length=20, null=True)),
                ('contract_starts', models.DateField(blank=True, null=True)),
                ('contract_ends', models.DateField(blank=True, null=True)),
                ('tax_or_wage', models.FloatField(default=0, null=True)),
                ('tax_type', models.BooleanField(choices=[(True, 'Per Person'), ('False', 'Per Apartment')], null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.building')),
            ],
        ),
        migrations.CreateModel(
            name='MainUtil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_counter', models.PositiveIntegerField(default=0, null=True)),
                ('util', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.utility')),
            ],
        ),
    ]
