# Generated by Django 3.1.7 on 2021-03-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_auto_20210326_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonutils',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
