# Generated by Django 3.1.7 on 2021-06-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_building_mainutil_utility'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='county',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='has_elevator',
            field=models.BooleanField(default=False),
        ),
    ]
