# Generated by Django 3.1.7 on 2021-03-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_commonutils_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonutils',
            name='util_tax',
            field=models.FloatField(default=0),
        ),
    ]
