# Generated by Django 3.1.7 on 2021-03-26 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_auto_20210326_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='attached_to',
            new_name='building',
        ),
        migrations.AddField(
            model_name='features',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='building.apartment'),
        ),
    ]
