# Generated by Django 3.1.7 on 2021-03-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0005_auto_20210326_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='current_month_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='payment_status',
            field=models.BooleanField(choices=[(True, 'Paid'), (False, 'Unpaid')], default=False, null=True),
        ),
    ]
