# Generated by Django 3.1.7 on 2021-03-26 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0006_auto_20210326_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='payment_status',
            field=models.BooleanField(choices=[(True, 'Paid'), (False, 'Unpaid')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
