# Generated by Django 3.1.7 on 2021-03-27 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0007_auto_20210326_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
        migrations.AddField(
            model_name='apartment',
            name='debt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commonutils',
            name='contract_ends',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='commonutils',
            name='contract_starts',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='commonutils',
            name='provider',
            field=models.CharField(blank=True, choices=[('City', 'City'), ('Company', 'Private')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commonutils',
            name='util_type',
            field=models.CharField(default='Common', max_length=20),
        ),
        migrations.AlterField(
            model_name='commonutils',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.apartment'),
        ),
        migrations.AlterField(
            model_name='commonutils',
            name='util_index',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commonutils',
            name='util_status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Disabled')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonutils',
            name='util_tax',
            field=models.FloatField(default=0, null=True),
        ),
    ]
