# Generated by Django 3.1.7 on 2021-03-27 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0008_auto_20210326_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonUtils',
            new_name='CommonUtil',
        ),
    ]
