# Generated by Django 3.1.7 on 2021-03-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0009_auto_20210326_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonutil',
            name='contract_ends',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonutil',
            name='contract_starts',
            field=models.DateField(blank=True, null=True),
        ),
    ]
