# Generated by Django 3.1.7 on 2021-03-27 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0010_auto_20210326_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonutil',
            name='apartment',
        ),
        migrations.CreateModel(
            name='LinkedCommonUtil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.apartment')),
                ('common_util', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.commonutil')),
            ],
        ),
    ]
