# Generated by Django 3.1.7 on 2021-03-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0011_auto_20210327_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonutil',
            name='util_index',
        ),
        migrations.RemoveField(
            model_name='commonutil',
            name='util_status',
        ),
        migrations.RemoveField(
            model_name='commonutil',
            name='util_tax',
        ),
        migrations.AlterField(
            model_name='commonutil',
            name='util_type',
            field=models.CharField(choices=[('Common', 'Common'), ('Self', 'Self')], max_length=20),
        ),
    ]
