# Generated by Django 3.1.7 on 2021-03-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0013_auto_20210328_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonutil',
            name='util_index',
        ),
        migrations.RemoveField(
            model_name='commonutil',
            name='util_status',
        ),
        migrations.AddField(
            model_name='linkedcommonutil',
            name='util_index',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='linkedcommonutil',
            name='util_status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Disabled')], default=True, null=True),
        ),
    ]
