# Generated by Django 3.1.7 on 2021-03-28 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0014_auto_20210328_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualUtil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='MutualUtil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('util_type', models.CharField(choices=[('Mutual', 'Mutual'), ('Individual', 'Individual')], max_length=50)),
                ('provider', models.CharField(choices=[('City', 'City'), ('Private', 'Private')], max_length=50)),
                ('contract_starts', models.DateField(blank=True, null=True)),
                ('contract_ends', models.DateField(blank=True, null=True)),
                ('util_tax_wage', models.FloatField(default=0, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.building')),
            ],
        ),
        migrations.RemoveField(
            model_name='feature',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='building',
        ),
        migrations.RemoveField(
            model_name='linkedcommonutil',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='linkedcommonutil',
            name='common_util',
        ),
        migrations.DeleteModel(
            name='CommonUtil',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='LinkedCommonUtil',
        ),
        migrations.AddField(
            model_name='mutualutil',
            name='common_util',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.utility'),
        ),
        migrations.AddField(
            model_name='individualutil',
            name='individual_util',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.utility'),
        ),
    ]
