# Generated by Django 3.1.7 on 2021-03-29 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0017_feature_featurelinked'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualutil',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Disabled')], default=False),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
