# Generated by Django 3.1.7 on 2021-03-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0018_auto_20210328_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualutil',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Disabled')], default=False, null=True),
        ),
    ]
