# Generated by Django 3.1.7 on 2021-03-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0019_auto_20210328_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualutil',
            name='monthly_payment',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mutualutil',
            name='monthly_payment',
            field=models.FloatField(default=0, null=True),
        ),
    ]
